trigger:
- main

pool:
  name: NavneetAgent

variables:
  BuildConfiguration: 'Release'
  AzureSubscription: 'MyServiceConnection'
  WebAppName: 'NavneetWebApp'

steps:

# Checkout source code
- checkout: self
  clean: true

# Install .NET 10 SDK
- task: UseDotNet@2
  displayName: 'Install .NET 10 SDK'
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

# Display repository structure (for troubleshooting)
- script: |
    echo Repository Location:
    echo $(Build.SourcesDirectory)
    dir "$(Build.SourcesDirectory)" /s
  displayName: 'Show Repository Structure'

# Restore Solution
- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: 'restore'
    projects: 'CICD.slnx'

# Build Solution
- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: 'CICD.slnx'
    arguments: '--configuration $(BuildConfiguration)'

# Execute Unit Tests
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: 'ProductTest/ProductTest.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-build'

# Publish Web API
- task: DotNetCoreCLI@2
  displayName: 'Publish Web API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'ProductService/ProductService.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# Publish Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Deploy to Azure Web App
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'MyServiceConnection'
    appName: 'NavneetWebApp'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'