trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: Release

steps:
- checkout: self

# Install .NET 10 SDK
- task: UseDotNet@2
  displayName: 'Install .NET 10 SDK'
  inputs:
    packageType: sdk
    version: '10.0.x'

# Verify repo structure
- powershell: |
    Write-Host "Build.SourcesDirectory=$(Build.SourcesDirectory)"
    Get-ChildItem "$(Build.SourcesDirectory)" -Recurse | Select-Object FullName
  displayName: 'List Repository Files'

# Restore
- task: DotNetCoreCLI@2
  displayName: 'Restore ProductService'
  inputs:
    command: restore
    projects: '**/src/ProductService/ProductService.csproj'

# Build
- task: DotNetCoreCLI@2
  displayName: 'Build ProductService'
  inputs:
    command: build
    projects: '**/src/ProductService/ProductService.csproj'
    arguments: '--configuration $(BuildConfiguration)'

# Test
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: test
    projects: '**/src/ProductTest/ProductTest.csproj'
    arguments: '--configuration $(BuildConfiguration)'

# Publish
- task: DotNetCoreCLI@2
  displayName: 'Publish ProductService'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/src/ProductService/ProductService.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# Deploy
- task: AzureWebApp@1
  displayName: 'Deploy to Azure'
  inputs:
    azureSubscription: 'MyServiceConnection'
    appName: 'NavneetWebApp'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
