trigger:
- main

pool:
  name: NavneetAgent

variables:

  BuildConfiguration: 'Release'
  AzureSubscription: 'MyServiceConnection'
  WebAppName: 'NavneetWebApp'

steps:

# Install .NET SDK

- task: UseDotNet@2
  displayName: Install .NET SDK

  inputs:
    packageType: sdk
    version: '8.x'

# Restore

- task: DotNetCoreCLI@2
  displayName: Restore Packages

  inputs:
    command: restore
    projects: '**/*.csproj'

# Build

- task: DotNetCoreCLI@2
  displayName: Build Project

  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

# Run Unit Tests

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests

  inputs:
    command: test
    projects: '**/*Test.csproj'
    arguments: '--configuration $(BuildConfiguration)'

# Publish

- task: DotNetCoreCLI@2
  displayName: Publish Web API

  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/ProductService.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# Publish Artifact

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifact

  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop

# Deploy Azure Web App

- task: AzureWebApp@1
  displayName: Deploy to Azure Web App

  inputs:
    azureSubscription: $(AzureSubscription)
    appName: $(WebAppName)
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'